validate proxy.extra_routes
jupyterhub/jupyterhub pull request #3967
Opened 2022-07-08 16:45 UTC by minrk

- add trailing slash if missing, and warn (as we do with url prefixes elsewhere), since this one is unambiguous
- raise if leading slash is wrong (must not be present with host routing, must be present otherwise). Raises rather than fixing automatically like trailing slash because it is ambiguous whether the intention is host-based routing or prefix routing.
- Lightweight check for probably-urls (don't need to be strict here, just catch likely errors, such as omitting host/protocol entirely)

Came up in https://discourse.jupyter.org/t/oauth-flow-in-jupyterhub-on-z2jh/14779/8

2022-07-10 10:30 UTC, consideRatio approved these changes

2022-07-10 10:32 UTC, consideRatio requested changes
@minrk I see that this includes an actual test failure of relevance.

```
E                   ValueError: Proxy.extra_routes missing host component in /prefix/ (must not have leading '/') when using `JupyterHub.subdomain_host = 'http://localhost.jovyan.org:8000/'`
```

2022-07-14 08:59 UTC, consideRatio approved these changes

2022-07-14 16:01 UTC, merged

2022-07-14 16:01 UTC, minrk commented
@consideRatio thanks for reviewiing! Sorry I missed the test failure for a while.